/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import clase.Estudiante;
import clase.ListaEstudiantes;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class AgregarEstudiantes extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarEstudiantes
     */
    private ListaEstudiantes listaestudiantes;

    public ListaEstudiantes getListaestudiantes() {
        return listaestudiantes;
    }

    public void setListaestudiantes(ListaEstudiantes listaestudiantes) {
        this.listaestudiantes = listaestudiantes;
    }

    private DefaultListModel<String> modeloLista = new DefaultListModel<>();

    public AgregarEstudiantes() {
        listaestudiantes = new ListaEstudiantes();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCarnet = new javax.swing.JLabel();
        lblFechaIngreso = new javax.swing.JLabel();
        lblFechaEgreso = new javax.swing.JLabel();
        lblIdCarrera = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        ftfFechaIngreso = new javax.swing.JFormattedTextField();
        ftfFechaEgreso = new javax.swing.JFormattedTextField();
        ftfFechaNacimiento = new javax.swing.JFormattedTextField();
        txfCarrera = new javax.swing.JTextField();
        txfCedula = new javax.swing.JTextField();
        txfNombre = new javax.swing.JTextField();
        txfDireccion = new javax.swing.JTextField();
        txfEmail = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        ftfTelefono = new javax.swing.JFormattedTextField();
        ftfCarnet = new javax.swing.JFormattedTextField();
        lstEstudiantes = new java.awt.List();

        setClosable(true);
        setTitle("Agregar Estudiante");
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Registro de Estudiantes");

        lblCarnet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCarnet.setText("Carnet:");

        lblFechaIngreso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaIngreso.setText("Fecha de Ingreso:");

        lblFechaEgreso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaEgreso.setText("Fecha de Egreso:");

        lblIdCarrera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdCarrera.setText("ID carrera:");

        lblCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCedula.setText("Cédula:");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaNacimiento.setText("Fecha de nacimiento:");

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDireccion.setText("Dirección:");

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefono.setText("Telefono:");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("Email:");

        ftfFechaIngreso.setEditable(false);
        try {
            ftfFechaIngreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfFechaIngresoActionPerformed(evt);
            }
        });

        ftfFechaEgreso.setEditable(false);
        try {
            ftfFechaEgreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfFechaEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfFechaEgresoActionPerformed(evt);
            }
        });

        ftfFechaNacimiento.setEditable(false);
        try {
            ftfFechaNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfFechaNacimientoActionPerformed(evt);
            }
        });

        txfCarrera.setEditable(false);
        txfCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCarreraActionPerformed(evt);
            }
        });

        txfCedula.setEditable(false);

        txfNombre.setEditable(false);
        txfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfNombreKeyTyped(evt);
            }
        });

        txfDireccion.setEditable(false);

        txfEmail.setEditable(false);
        txfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfEmailKeyTyped(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        ftfTelefono.setEditable(false);
        try {
            ftfTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfTelefonoActionPerformed(evt);
            }
        });

        ftfCarnet.setEditable(false);
        try {
            ftfCarnet.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfCarnetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfFechaIngreso)
                            .addComponent(ftfFechaEgreso)
                            .addComponent(ftfFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfCarrera)
                            .addComponent(txfCedula)
                            .addComponent(txfNombre)
                            .addComponent(txfDireccion)
                            .addComponent(txfEmail)
                            .addComponent(ftfTelefono)
                            .addComponent(ftfCarnet, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(293, 293, 293))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfFechaEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lstEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstEstudiantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lstEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lstEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftfFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfFechaIngresoActionPerformed

    private void ftfFechaEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfFechaEgresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfFechaEgresoActionPerformed

    private void ftfFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfFechaNacimientoActionPerformed

    private void txfCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCarreraActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int selectedIndex = lstEstudiantes.getSelectedIndex();
            if (selectedIndex == -1) {
                JOptionPane.showMessageDialog(this, "Selecciona un estudiante de la lista para eliminar");
                return;
            }

            // Obtener el carnet del texto (antes del " -")
            String item = lstEstudiantes.getItem(selectedIndex);
            int carnet = Integer.parseInt(item.split(" -")[0].trim());

            boolean eliminado = listaestudiantes.eliminarPorCarnet(carnet);
            if (eliminado) {
                lstEstudiantes.remove(selectedIndex); // ✅ borra visualmente
                JOptionPane.showMessageDialog(this, "Estudiante eliminado correctamente ✅");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un estudiante con ese carnet ❌");
            }

            // limpiar campos
            ftfCarnet.setText("");
            ftfFechaIngreso.setText("");
            ftfFechaEgreso.setText("");
            txfCarrera.setText("");
            txfCedula.setText("");
            txfNombre.setText("");
            ftfFechaNacimiento.setText("");
            txfDireccion.setText("");
            ftfTelefono.setText("");
            txfEmail.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar estudiante", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Si NO está editable, este botón pasa a "modo edición"
        if (!txfEmail.isEditable()) {
            ftfFechaIngreso.setEditable(true);
            ftfFechaEgreso.setEditable(true);
            ftfFechaNacimiento.setEditable(true);
            ftfCarnet.setEditable(true);
            txfCarrera.setEditable(true);
            txfCedula.setEditable(true);
            txfNombre.setEditable(true);
            txfDireccion.setEditable(true);
            ftfTelefono.setEditable(true);
            txfEmail.setEditable(true);
            btnBuscar.setEnabled(false);
            btnEliminar.setEnabled(false);
            return;
        }

        // Guardar
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        try {
            int carnet = Integer.parseInt(ftfCarnet.getText().trim());
            LocalDate fechaIngreso = LocalDate.parse(ftfFechaIngreso.getText().trim(), formatter);
            LocalDate fechaEgreso = LocalDate.parse(ftfFechaEgreso.getText().trim(), formatter);
            String idCarrera = txfCarrera.getText().trim();
            String cedula = txfCedula.getText().trim();
            String nombre = txfNombre.getText().trim();
            LocalDate fechaNacimiento = LocalDate.parse(ftfFechaNacimiento.getText().trim(), formatter);
            String direccion = txfDireccion.getText().trim();
            String email = txfEmail.getText().trim();
            int telefono = Integer.parseInt(ftfTelefono.getText().trim());

            Estudiante estudiante = new Estudiante(
                    carnet, fechaIngreso, fechaEgreso, idCarrera, cedula,
                    nombre, fechaNacimiento, direccion, telefono, email
            );

            // Persistir en tu lista
            listaestudiantes.agregarEstudiante(estudiante);

            // **AÑADIR A LA LISTA DE LA DERECHA (java.awt.List)**
            lstEstudiantes.add(estudiante.getCarnet() + " - " + estudiante.getNombre());

            // Limpiar y bloquear edición
            ftfFechaIngreso.setText("");
            ftfFechaEgreso.setText("");
            ftfFechaNacimiento.setText("");
            ftfCarnet.setText("");
            txfCarrera.setText("");
            txfCedula.setText("");
            txfNombre.setText("");
            txfDireccion.setText("");
            ftfTelefono.setText("");
            txfEmail.setText("");

            ftfFechaIngreso.setEditable(false);
            ftfFechaEgreso.setEditable(false);
            ftfFechaNacimiento.setEditable(false);
            ftfCarnet.setEditable(false);
            txfCarrera.setEditable(false);
            txfCedula.setEditable(false);
            txfNombre.setEditable(false);
            txfDireccion.setEditable(false);
            ftfTelefono.setEditable(false);
            txfEmail.setEditable(false);
            btnBuscar.setEnabled(true);
            btnEliminar.setEnabled(true);

            JOptionPane.showMessageDialog(this, "Estudiante guardado ✅");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Verifica números y fechas (formato dd-MM-yyyy).",
                    "Datos inválidos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void ftfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfTelefonoActionPerformed

    private void ftfCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfCarnetActionPerformed

    private void txfEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfEmailKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && c != '@' && c != '.') {
            evt.consume();
        }    }//GEN-LAST:event_txfEmailKeyTyped

    private void txfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNombreKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ') {
            evt.consume();
        }    }//GEN-LAST:event_txfNombreKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        try {
            int carnet = Integer.parseInt(ftfCarnet.getText().trim());
            Estudiante estudiante = listaestudiantes.obtenerPorCarnet(carnet);

            if (estudiante != null) {
                DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd-MM-yyyy");

                ftfFechaIngreso.setText(estudiante.getFechaIngreso().format(fmt));
                ftfFechaEgreso.setText(estudiante.getFechaEgreso().format(fmt));
                txfCarrera.setText(estudiante.getIdCarrera());
                txfCedula.setText(estudiante.getCedula());
                txfNombre.setText(estudiante.getNombre());
                ftfFechaNacimiento.setText(estudiante.getFecNac().format(fmt));
                txfDireccion.setText(estudiante.getDireccion());
                ftfTelefono.setText(String.valueOf(estudiante.getTelefono()));
                txfEmail.setText(estudiante.getEmail());

                JOptionPane.showMessageDialog(this, "Estudiante encontrado");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un estudiante con ese carnet");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Carnet inválido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void lstEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstEstudiantesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JFormattedTextField ftfCarnet;
    private javax.swing.JFormattedTextField ftfFechaEgreso;
    private javax.swing.JFormattedTextField ftfFechaIngreso;
    private javax.swing.JFormattedTextField ftfFechaNacimiento;
    private javax.swing.JFormattedTextField ftfTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFechaEgreso;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblIdCarrera;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private java.awt.List lstEstudiantes;
    private javax.swing.JTextField txfCarrera;
    private javax.swing.JTextField txfCedula;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfNombre;
    // End of variables declaration//GEN-END:variables
}
